# Generated by Django 5.2 on 2025-05-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_book_userbook'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userbook',
            unique_together={('user', 'book')},
        ),
    ]
